version: 2.1
orbs:
  python: circleci/python@0.2.1
  slack: circleci/slack@4.1

jobs:
  build-test-deploy:
    docker:
      - image: circleci/python:3.8.2  # primary container for the build job
        auth:
          username: polycole
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run:
          name: Build and push Docker image to Heroku
          command: |
            sudo curl https://cli-assets.heroku.com/install.sh | sh
            docker ps
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:login
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:push -a wooglin-bot web
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:release -a wooglin-bot web
      - slack/notify:
          channel: $SLACK_DEFAULT_CHANNEL
          custom: |
            {
                "blocks": [
                    {
                        "type": "header",
                        "text": {
                            "type": "plain_text",
                            "text": ":robot_face: Wooglin-bot Deployment Successful! :tada:",
                            "emoji": true
                        }
                    },
                    {
                        "type": "section",
                        "fields": [
                            {
                                "type": "mrkdwn",
                                "text": "*Project*:\n$CIRCLE_PROJECT_REPONAME"
                            },
                            {
                                "type": "mrkdwn",
                                "text": "*When*:\n$(date +'%m/%d/%Y %T')"
                            },
                            {
                                "type": "mrkdwn",
                                "text": "*Tag*:\n$CIRCLE_TAG"
                            },
                            {
                                "type": "mrkdwn",
                                "text": "*Branch*:\n$CIRCLE_BRANCH"
                            },
                            {
                                "type": "mrkdwn",
                                "text": "*Author*:\n$CIRCLE_USERNAME"
                            }
                        ],
                        "accessory": {
                            "type": "image",
                            "image_url": "https://i.imgur.com/olHpRLd.jpg",
                            "alt_text": "Wooglin CI Success Logo"
                        }
                    },
                    {
                        "type": "actions",
                        "elements": [
                            {
                                "type": "button",
                                "text": {
                                    "type": "plain_text",
                                    "text": "View Job"
                                },
                                "url": "${CIRCLE_BUILD_URL}"
                            }
                        ]
                    }
                ]
            }
          event: pass
      - slack/notify:
          channel: $SLACK_DEFAULT_CHANNEL
          custom: |
            {
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": ":robot_face: Wooglin-bot Deployment Failed :red_circle:",
                    "emoji": true
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Job*: ${CIRCLE_JOB}"
                    }
                  ]
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Project*:\n$CIRCLE_PROJECT_REPONAME"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*When*:\n$(date +'%m/%d/%Y %T')"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Branch*:\n$CIRCLE_BRANCH"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Author*:\n$CIRCLE_USERNAME"
                    }
                  ],
                  "accessory": {
                    "type": "image",
                    "image_url": "https://i.imgur.com/CXDfXUB.jpg",
                    "alt_text": "Wooglin CI Failure Logo"
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Mentions*:\n$SLACK_PARAM_MENTIONS"
                    }
                  ]
                },
                {
                  "type": "actions",
                  "elements": [
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": "View Job"
                      },
                      "url": "${CIRCLE_BUILD_URL}"
                    }
                  ]
                }
              ]
            }
          event: fail

workflows:
  main:
    jobs:
      - build-test-deploy
